zabbix_1:
  addr: '192.168.0.29'  # Address of zabbix 1
  token: '1eb1a810f7ecaa0d6e33a30fe43d0f5a849aa31ff6ac5ddfc6bb88e02efa2326' # Token id generate in zabbix -> administration -> General -> API Token
  type: 'ref'  # 'ref' for original zabbix or 'cpy' for copy zabbix

zabbix_2:
  addr: '192.168.0.31'  # Address of zabbix 1
  token: 'a66bfc4d120a5357ec2b75cfab84be67b9eb8c52c76dbc4d1f4e9cfebb33bc0d' # Token id generate in zabbix -> administration -> General -> API Token
  type: 'cpy'  # 'ref' for original zabbix or 'cpy' for copy zabbix

